### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SuperEngineer64** [WondrousLLC/fractal-twig-drupal-adapter#4]
Hey!

Iam trying for some hours now to include twig into fractal, but it doesnt work. Fractal just shows me the plain twig code and don't interpretate it.

Are there more installation steps required then listed in the documentation?

cheers!

**Comment by tassilogroeper** [comment]
Hi @SuperEngineer64 ,

can you provide a minimal example of how you implemented it?
My first guess: what is your file ending? Inside the components folder only use `*.twig` files. Do not use the drupal way `*.html.twig`.

greetings
